version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 3
  reviewers:
  - superliuwr
